name: Deploy to Posit Connect

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps + rsconnect & write manifest
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install rsconnect-python
          # Write a Connect manifest so GitHub runner knows how to package your Flask app
          rsconnect write-manifest flask .

      - name: Deploy to Posit Connect
        env:
          CONNECT_SERVER: ${{ secrets.CONNECT_SERVER }}
          CONNECT_API_KEY: ${{ secrets.CONNECT_API_KEY }}
        run: |
          # Add the Connect server with your API key (nickname: pc)
          rsconnect add --server "$CONNECT_SERVER" --api-key "$CONNECT_API_KEY" --name pc
          # Deploy Flask app from repo root; WSGI entrypoint is module:object
          rsconnect deploy flask . -n pc --title "KnockKnock Intelligence" --entrypoint app_simple:app -v
