name: Deploy to Posit Connect

on:
  push:
    branches: [ "main" ]  # change to your default branch if not main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps + rsconnect & write manifest
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install rsconnect-python
          rsconnect write-manifest flask .

      - name: Deploy to Posit Connect
        env:
          CONNECT_SERVER: ${{ secrets.CONNECT_SERVER }}
          CONNECT_API_KEY: ${{ secrets.CONNECT_API_KEY }}
        run: |
          rsconnect add --server "$CONNECT_SERVER" --api-key "$CONNECT_API_KEY" --name pc
          rsconnect deploy flask . -n pc --title "KnockKnock Intelligence" --entrypoint app_simple:app -v
