name: Deploy to Posit Connect

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps + rsconnect & write manifest
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install rsconnect-python
          # Create/refresh a manifest for Flask so Connect knows how to run it
          rsconnect write-manifest flask .

      - name: Deploy to Posit Connect (no nickname; pass server+key explicitly)
        env:
          CONNECT_SERVER: ${{ secrets.CONNECT_SERVER }}
          CONNECT_API_KEY: ${{ secrets.CONNECT_API_KEY }}
        run: |
          rsconnect deploy flask . \
            --server "$CONNECT_SERVER" \
            --api-key "$CONNECT_API_KEY" \
            --title "KnockKnock Intelligence" \
            --entrypoint app_simple:app \
            -v
