name: Deploy to Posit Connect

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps + rsconnect and write manifest
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install rsconnect-python
          # Optional: generate/update manifest locally
          rsconnect write-manifest flask .

      # If your Connect is behind a corp CA/proxy, insert that setup step here.

      - name: Deploy Flask app to Posit Connect
        env:
          CONNECT_SERVER: ${{ secrets.CONNECT_SERVER }}
          CONNECT_API_KEY: ${{ secrets.CONNECT_API_KEY }}
        run: |
          rsconnect deploy flask . \
            --server "$CONNECT_SERVER" \
            --api-key "$CONNECT_API_KEY" \
            --title "KnockKnock Intelligence" \
            --entrypoint app_simple:app \
            --no-verify \
            -v
